// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable no-irregular-whitespace, @typescript-eslint/ban-types -- auto-generated by typesafe-i18n */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'zh'

export type Locales =
	| 'en'
	| 'fr'
	| 'zh'
	| 'zh-TW'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	commands: {
		/**
		 * 启​用​/​禁​用​目​录
		 */
		enableDisableToc: string
		/**
		 * 打​开​目​录​侧​边​视​图
		 */
		openTocView: string
		/**
		 * 返​回​光​标​位​置
		 */
		returnToCursor: string
		/**
		 * 滚​动​到​顶​部
		 */
		scrollToTop: string
		/**
		 * 滚​动​到​底​部
		 */
		scrollToBottom: string
		/**
		 * 导​航​到​上​一​个​标​题
		 */
		navigatePreviousHeading: string
		/**
		 * 导​航​到​下​一​个​标​题
		 */
		navigateNextHeading: string
		/**
		 * 展​开​/​收​起​目​录
		 */
		tocExpand: string
		/**
		 * 插​入​阅​读​时​间​卡​片
		 */
		insertReadingTimeCard: string
		/**
		 * 插​入​目​录​卡​片
		 */
		insertTableOfContentsCard: string
		/**
		 * 添​加​/​移​除​当​前​文​件​到​标​题​编​号​黑​名​单
		 */
		addCurrentFileToHideHeadingNumberBlacklist: string
		/**
		 * 添​加​/​移​除​当​前​文​件​夹​到​标​题​编​号​黑​名​单
		 */
		addCurrentFolderToHideHeadingNumberBlacklist: string
	}
	notices: {
		/**
		 * 已​被​现​有​规​则​覆​盖
		 */
		alreadyCovered: string
		/**
		 * 已​添​加
		 */
		added: string
		/**
		 * 已​添​加​，​并​移​除​了​ ​{​c​o​u​n​t​}​ ​个​冗​余​规​则
		 * @param {number} count
		 */
		addedAndRemovedRedundant: RequiredParams<'count'>
		/**
		 * 不​在​黑​名​单​中
		 */
		notInBlacklist: string
		/**
		 * 已​移​除
		 */
		removed: string
		/**
		 * 已​被​某​个​规​则​覆​盖​，​如​需​移​除​请​手​动​删​除​该​规​则
		 */
		coveredByPattern: string
		/**
		 * 已​移​动​「​{​h​e​a​d​i​n​g​}​」
		 * @param {unknown} heading
		 */
		reorderSuccess: RequiredParams<'heading'>
		/**
		 * 移​动​失​败​：​未​找​到​文​件
		 */
		reorderFailedNoFile: string
		/**
		 * 移​动​失​败​：​标​题​索​引​超​出​范​围
		 */
		reorderFailedInvalidIndex: string
		/**
		 * 移​动​失​败​：​源​位​置​与​目​标​位​置​相​同
		 */
		reorderFailedSamePosition: string
		/**
		 * 移​动​失​败​：​不​能​将​标​题​移​入​自​身​子​树​内
		 */
		reorderFailedTargetIsDescendant: string
		/**
		 * 移​动​失​败​：​文​档​没​有​标​题
		 */
		reorderFailedNoHeadings: string
		/**
		 * 移​动​失​败​：​编​辑​器​操​作​失​败
		 */
		reorderFailedEditor: string
	}
	view: {
		/**
		 * 未​找​到​标​题​，​请​确​保​当​前​文​档​包​含​标​题​，​或​者​激​活​m​a​r​k​d​o​w​n​文​档​视​图​。
		 */
		view_empty: string
	}
	settings: {
		toc: {
			/**
			 * 目​录
			 */
			name: string
			show: {
				/**
				 * 显​示​目​录
				 */
				name: string
				/**
				 * 启​用​或​禁​用​目​录​功​能
				 */
				desc: string
			}
			alwaysExpand: {
				/**
				 * 始​终​展​开​目​录
				 */
				name: string
				/**
				 * 启​用​或​禁​用​始​终​展​开​目​录​，​可​使​用​文​档​属​性​ ​`​c​s​s​c​l​a​s​s​e​s​`​ ​来​控​制​显​示​与​隐​藏​：
				 */
				desc: string
			}
			renderInAllVisibleViews: {
				/**
				 * 在​所​有​可​见​视​图​中​渲​染​目​录
				 */
				name: string
				/**
				 * 开​启​后​，​会​在​所​有​当​前​可​见​的​ ​M​a​r​k​d​o​w​n​ ​视​图​中​显​示​内​联​目​录​；​关​闭​时​仅​在​当​前​活​动​视​图​中​显​示​。​默​认​关​闭​以​避​免​额​外​渲​染​开​销​。
				 */
				desc: string
			}
			width: {
				/**
				 * 目​录​宽​度
				 */
				name: string
				/**
				 * 设​置​目​录​的​宽​度
				 */
				desc: string
			}
			position: {
				/**
				 * 目​录​位​置
				 */
				name: string
				/**
				 * 设​置​目​录​的​位​置
				 */
				desc: string
				options: {
					/**
					 * 左​侧
					 */
					left: string
					/**
					 * 右​侧
					 */
					right: string
				}
			}
			offset: {
				/**
				 * 目​录​偏​移
				 */
				name: string
				/**
				 * 设​置​目​录​的​偏​移​量
				 */
				desc: string
			}
			offsetY: {
				/**
				 * 目​录​纵​向​偏​移
				 */
				name: string
				/**
				 * 设​置​目​录​的​纵​向​偏​移​量
				 */
				desc: string
			}
			indicatorMode: {
				/**
				 * 指​示​器​模​式
				 */
				name: string
				/**
				 * 设​置​目​录​收​起​时​指​示​器​的​显​示​模​式
				 */
				desc: string
				options: {
					/**
					 * 长​条
					 */
					bar: string
					/**
					 * 圆​点
					 */
					dot: string
					/**
					 * 隐​藏
					 */
					hidden: string
				}
			}
		}
		render: {
			/**
			 * 渲​染
			 */
			name: string
			useHeadingNumber: {
				/**
				 * 使​用​标​题​编​号
				 */
				name: string
				/**
				 * 启​用​或​禁​用​在​目​录​中​使​用​标​题​编​号​，​可​使​用​文​档​属​性​ ​`​c​s​s​c​l​a​s​s​e​s​`​ ​来​控​制​显​示​与​隐​藏​（​优​先​级​高​于​黑​名​单​）​：
				 */
				desc: string
			}
			numberingStartIndex: {
				/**
				 * 标​题​编​号​起​始​序​号
				 */
				name: string
				/**
				 * 选​择​标​题​编​号​是​从​ ​0​ ​开​始​还​是​从​ ​1​ ​开​始​。
				 */
				desc: string
				options: {
					/**
					 * 0
					 */
					zero: string
					/**
					 * 1
					 */
					one: string
				}
			}
			skipHeadingLevels: {
				/**
				 * 跳​过​标​题​层​级
				 */
				name: string
				/**
				 * 选​择​在​目​录​中​需​要​跳​过​的​标​题​层​级
				 */
				desc: string
			}
			renderMarkdown: {
				/**
				 * 渲​染​ ​M​a​r​k​d​o​w​n
				 */
				name: string
				/**
				 * 启​用​或​禁​用​在​目​录​中​渲​染​ ​M​a​r​k​d​o​w​n
				 */
				desc: string
			}
			showWhenSingleHeading: {
				/**
				 * 单​一​标​题​时​显​示​目​录
				 */
				name: string
				/**
				 * 启​用​或​禁​用​在​文​档​仅​有​单​一​标​题​时​显​示​目​录
				 */
				desc: string
			}
			hideHeadingNumberBlacklist: {
				/**
				 * 标​题​编​号​黑​名​单
				 */
				name: string
				/**
				 * 指​定​需​要​隐​藏​标​题​编​号​的​文​件​（​每​行​一​个​路​径​）​。​支​持​通​配​符​：​*​ ​(​任​意​字​符​)​，​?​ ​(​单​个​字​符​)​。​仅​在​「​使​用​标​题​编​号​」​开​启​时​生​效​。​示​例​：​f​o​l​d​e​r​/​f​i​l​e​.​m​d​ ​或​ ​*​.​m​d
				 */
				desc: string
			}
			enableDragSort: {
				/**
				 * 启​用​拖​拽​排​序
				 */
				name: string
				/**
				 * 允​许​在​目​录​中​拖​拽​标​题​来​重​新​排​序​文​档​章​节​内​容
				 */
				desc: string
			}
		}
		tool: {
			/**
			 * 工​具
			 */
			name: string
			headings: {
				/**
				 * 文​档​导​航​按​钮
				 */
				returnButtons: string
				/**
				 * 目​录​工​具​栏​按​钮
				 */
				toolbarButtons: string
			}
			useToolbar: {
				/**
				 * 使​用​工​具​栏
				 */
				name: string
				/**
				 * 显​示​用​于​控​制​目​录​的​工​具​栏​（​固​定​、​位​置​、​展​开​、​偏​移​、​复​制​）
				 */
				desc: string
			}
			toolbarAlwaysShow: {
				/**
				 * 目​录​工​具​栏​常​驻​显​示
				 */
				name: string
				/**
				 * 目​录​展​开​时​，​目​录​工​具​栏​始​终​可​见​，​无​需​悬​停​触​发
				 */
				desc: string
			}
			showProgressBar: {
				/**
				 * 显​示​进​度​条
				 */
				name: string
				/**
				 * 在​目​录​上​方​显​示​阅​读​进​度
				 */
				desc: string
			}
			showProgressCircle: {
				/**
				 * 显​示​进​度​圆​环
				 */
				name: string
				/**
				 * 在​指​示​器​上​方​显​示​阅​读​进​度​，​即​收​缩​目​录​后
				 */
				desc: string
			}
			toolbarButtons: {
				pinTOC: {
					/**
					 * 固​定​/​取​消​固​定​目​录
					 */
					name: string
					/**
					 * 切​换​目​录​是​否​常​驻​展​开
					 */
					desc: string
				}
				changePosition: {
					/**
					 * 更​改​位​置
					 */
					name: string
					/**
					 * 在​左​右​两​侧​之​间​切​换​目​录​位​置
					 */
					desc: string
				}
				expandCollapse: {
					/**
					 * 展​开​/​收​起​目​录​项
					 */
					name: string
					/**
					 * 一​键​展​开​或​收​起​所​有​目​录​项
					 */
					desc: string
				}
				leftOffset: {
					/**
					 * 向​左​偏​移
					 */
					name: string
					/**
					 * 将​目​录​向​左​移​动​一​步
					 */
					desc: string
				}
				rightOffset: {
					/**
					 * 向​右​偏​移
					 */
					name: string
					/**
					 * 将​目​录​向​右​移​动​一​步
					 */
					desc: string
				}
				upOffset: {
					/**
					 * 向​上​移​动
					 */
					name: string
					/**
					 * 将​目​录​向​上​移​动​一​步
					 */
					desc: string
				}
				downOffset: {
					/**
					 * 向​下​移​动
					 */
					name: string
					/**
					 * 将​目​录​向​下​移​动​一​步
					 */
					desc: string
				}
				locateActiveHeading: {
					/**
					 * 定​位​到​当​前​标​题
					 */
					name: string
					/**
					 * 滚​动​目​录​列​表​，​使​当​前​活​动​的​标​题​进​入​可​视​范​围
					 */
					desc: string
				}
				copyTOC: {
					/**
					 * 复​制​目​录
					 */
					name: string
					/**
					 * 将​目​录​复​制​到​剪​贴​板
					 */
					desc: string
				}
			}
			returnToCursor: {
				/**
				 * 返​回​光​标
				 */
				name: string
				/**
				 * 返​回​到​上​次​光​标​位​置​的​按​钮​（​仅​在​编​辑​模​式​下​可​用​）
				 */
				desc: string
			}
			returnToTop: {
				/**
				 * 返​回​顶​部
				 */
				name: string
				/**
				 * 返​回​到​文​档​顶​部​的​按​钮
				 */
				desc: string
			}
			returnToBottom: {
				/**
				 * 返​回​底​部
				 */
				name: string
				/**
				 * 返​回​到​文​档​底​部​的​按​钮
				 */
				desc: string
			}
			jumpToNextHeading: {
				/**
				 * 跳​转​到​下​一​个​标​题
				 */
				name: string
				/**
				 * 跳​转​到​下​一​个​标​题​的​按​钮
				 */
				desc: string
			}
			jumpToPrevHeading: {
				/**
				 * 跳​转​到​上​一​个​标​题
				 */
				name: string
				/**
				 * 跳​转​到​上​一​个​标​题​的​按​钮
				 */
				desc: string
			}
		}
	}
	cards: {
		/**
		 * 预​览
		 */
		preview: string
		/**
		 * 属​性
		 */
		property: string
		/**
		 * 基​本​设​置
		 */
		basicSetting: string
		/**
		 * 样​式​设​置
		 */
		styleSetting: string
		readingTimeCard: {
			/**
			 * 阅​读​时​间​卡​片​设​置
			 */
			heading: string
			/**
			 * 标​题
			 */
			title: string
			/**
			 * 每​分​钟​中​文​单​词​数
			 */
			chineseWordsPerMinute: string
			/**
			 * 每​分​钟​英​文​单​词​数
			 */
			englishWordsPerMinute: string
			/**
			 * 阅​读​时​间​前​的​文​本
			 */
			textBefore: string
			/**
			 * 阅​读​时​间​后​的​文​本
			 */
			textAfter: string
			/**
			 * 图​标​名​称​（​来​自​O​b​s​i​d​i​a​n​图​标​集​）
			 */
			iconName: string
			/**
			 * 移​除​代​码​块
			 */
			removeCodeBlocks: string
			/**
			 * 移​除​w​i​k​i​链​接
			 */
			removeWikiLinks: string
			/**
			 * 移​除​图​片​链​接
			 */
			removeImageLinks: string
			/**
			 * 移​除​普​通​链​接
			 */
			removeNormalLinks: string
			/**
			 * 显​示​字​数
			 */
			showWordCount: string
		}
		tableOfContentsCard: {
			/**
			 * 目​录​卡​片​设​置
			 */
			heading: string
			/**
			 * 标​题
			 */
			title: string
			/**
			 * 最​小​标​题​深​度
			 */
			minDepth: string
			/**
			 * 最​大​标​题​深​度
			 */
			maxDepth: string
			/**
			 * 启​用​标​题​重​定​向
			 */
			redirect: string
			/**
			 * 显​示​标​题​编​号
			 */
			showNumbers: string
			/**
			 * 使​目​录​可​折​叠
			 */
			collapsible: string
		}
		styles: {
			/**
			 * 当​前​属​性
			 */
			currentProperties: string
			/**
			 * 添​加​新​属​性
			 */
			addNewProperty: string
			/**
			 * 未​定​义​自​定​义​属​性
			 */
			noneCustomProperty: string
		}
	}
	tools: {
		/**
		 * 固​定​/​取​消​固​定​目​录
		 */
		pinTOC: string
		/**
		 * 更​改​目​录​位​置
		 */
		changePosition: string
		/**
		 * 展​开​/​收​起​目​录​项
		 */
		expandCollapse: string
		/**
		 * 向​左​偏​移
		 */
		leftOffset: string
		/**
		 * 向​右​偏​移
		 */
		rightOffset: string
		/**
		 * 向​上​移​动
		 */
		upOffset: string
		/**
		 * 向​下​移​动
		 */
		downOffset: string
		/**
		 * 定​位​到​当​前​标​题
		 */
		locateActiveHeading: string
		/**
		 * 复​制​目​录​到​剪​贴​板
		 */
		copyTOC: string
		/**
		 * 返​回​导​航
		 */
		returnNavigation: string
		/**
		 * 返​回​光​标​位​置
		 */
		returnToCursor: string
		/**
		 * 返​回​顶​部
		 */
		returnToTop: string
		/**
		 * 返​回​底​部
		 */
		returnToBottom: string
		/**
		 * 下​一​个​标​题
		 */
		jumpToNextHeading: string
		/**
		 * 上​一​个​标​题
		 */
		jumpToPrevHeading: string
	}
}

export type TranslationFunctions = {
	commands: {
		/**
		 * 启用/禁用目录
		 */
		enableDisableToc: () => LocalizedString
		/**
		 * 打开目录侧边视图
		 */
		openTocView: () => LocalizedString
		/**
		 * 返回光标位置
		 */
		returnToCursor: () => LocalizedString
		/**
		 * 滚动到顶部
		 */
		scrollToTop: () => LocalizedString
		/**
		 * 滚动到底部
		 */
		scrollToBottom: () => LocalizedString
		/**
		 * 导航到上一个标题
		 */
		navigatePreviousHeading: () => LocalizedString
		/**
		 * 导航到下一个标题
		 */
		navigateNextHeading: () => LocalizedString
		/**
		 * 展开/收起目录
		 */
		tocExpand: () => LocalizedString
		/**
		 * 插入阅读时间卡片
		 */
		insertReadingTimeCard: () => LocalizedString
		/**
		 * 插入目录卡片
		 */
		insertTableOfContentsCard: () => LocalizedString
		/**
		 * 添加/移除当前文件到标题编号黑名单
		 */
		addCurrentFileToHideHeadingNumberBlacklist: () => LocalizedString
		/**
		 * 添加/移除当前文件夹到标题编号黑名单
		 */
		addCurrentFolderToHideHeadingNumberBlacklist: () => LocalizedString
	}
	notices: {
		/**
		 * 已被现有规则覆盖
		 */
		alreadyCovered: () => LocalizedString
		/**
		 * 已添加
		 */
		added: () => LocalizedString
		/**
		 * 已添加，并移除了 {count} 个冗余规则
		 */
		addedAndRemovedRedundant: (arg: { count: number }) => LocalizedString
		/**
		 * 不在黑名单中
		 */
		notInBlacklist: () => LocalizedString
		/**
		 * 已移除
		 */
		removed: () => LocalizedString
		/**
		 * 已被某个规则覆盖，如需移除请手动删除该规则
		 */
		coveredByPattern: () => LocalizedString
		/**
		 * 已移动「{heading}」
		 */
		reorderSuccess: (arg: { heading: unknown }) => LocalizedString
		/**
		 * 移动失败：未找到文件
		 */
		reorderFailedNoFile: () => LocalizedString
		/**
		 * 移动失败：标题索引超出范围
		 */
		reorderFailedInvalidIndex: () => LocalizedString
		/**
		 * 移动失败：源位置与目标位置相同
		 */
		reorderFailedSamePosition: () => LocalizedString
		/**
		 * 移动失败：不能将标题移入自身子树内
		 */
		reorderFailedTargetIsDescendant: () => LocalizedString
		/**
		 * 移动失败：文档没有标题
		 */
		reorderFailedNoHeadings: () => LocalizedString
		/**
		 * 移动失败：编辑器操作失败
		 */
		reorderFailedEditor: () => LocalizedString
	}
	view: {
		/**
		 * 未找到标题，请确保当前文档包含标题，或者激活markdown文档视图。
		 */
		view_empty: () => LocalizedString
	}
	settings: {
		toc: {
			/**
			 * 目录
			 */
			name: () => LocalizedString
			show: {
				/**
				 * 显示目录
				 */
				name: () => LocalizedString
				/**
				 * 启用或禁用目录功能
				 */
				desc: () => LocalizedString
			}
			alwaysExpand: {
				/**
				 * 始终展开目录
				 */
				name: () => LocalizedString
				/**
				 * 启用或禁用始终展开目录，可使用文档属性 `cssclasses` 来控制显示与隐藏：
				 */
				desc: () => LocalizedString
			}
			renderInAllVisibleViews: {
				/**
				 * 在所有可见视图中渲染目录
				 */
				name: () => LocalizedString
				/**
				 * 开启后，会在所有当前可见的 Markdown 视图中显示内联目录；关闭时仅在当前活动视图中显示。默认关闭以避免额外渲染开销。
				 */
				desc: () => LocalizedString
			}
			width: {
				/**
				 * 目录宽度
				 */
				name: () => LocalizedString
				/**
				 * 设置目录的宽度
				 */
				desc: () => LocalizedString
			}
			position: {
				/**
				 * 目录位置
				 */
				name: () => LocalizedString
				/**
				 * 设置目录的位置
				 */
				desc: () => LocalizedString
				options: {
					/**
					 * 左侧
					 */
					left: () => LocalizedString
					/**
					 * 右侧
					 */
					right: () => LocalizedString
				}
			}
			offset: {
				/**
				 * 目录偏移
				 */
				name: () => LocalizedString
				/**
				 * 设置目录的偏移量
				 */
				desc: () => LocalizedString
			}
			offsetY: {
				/**
				 * 目录纵向偏移
				 */
				name: () => LocalizedString
				/**
				 * 设置目录的纵向偏移量
				 */
				desc: () => LocalizedString
			}
			indicatorMode: {
				/**
				 * 指示器模式
				 */
				name: () => LocalizedString
				/**
				 * 设置目录收起时指示器的显示模式
				 */
				desc: () => LocalizedString
				options: {
					/**
					 * 长条
					 */
					bar: () => LocalizedString
					/**
					 * 圆点
					 */
					dot: () => LocalizedString
					/**
					 * 隐藏
					 */
					hidden: () => LocalizedString
				}
			}
		}
		render: {
			/**
			 * 渲染
			 */
			name: () => LocalizedString
			useHeadingNumber: {
				/**
				 * 使用标题编号
				 */
				name: () => LocalizedString
				/**
				 * 启用或禁用在目录中使用标题编号，可使用文档属性 `cssclasses` 来控制显示与隐藏（优先级高于黑名单）：
				 */
				desc: () => LocalizedString
			}
			numberingStartIndex: {
				/**
				 * 标题编号起始序号
				 */
				name: () => LocalizedString
				/**
				 * 选择标题编号是从 0 开始还是从 1 开始。
				 */
				desc: () => LocalizedString
				options: {
					/**
					 * 0
					 */
					zero: () => LocalizedString
					/**
					 * 1
					 */
					one: () => LocalizedString
				}
			}
			skipHeadingLevels: {
				/**
				 * 跳过标题层级
				 */
				name: () => LocalizedString
				/**
				 * 选择在目录中需要跳过的标题层级
				 */
				desc: () => LocalizedString
			}
			renderMarkdown: {
				/**
				 * 渲染 Markdown
				 */
				name: () => LocalizedString
				/**
				 * 启用或禁用在目录中渲染 Markdown
				 */
				desc: () => LocalizedString
			}
			showWhenSingleHeading: {
				/**
				 * 单一标题时显示目录
				 */
				name: () => LocalizedString
				/**
				 * 启用或禁用在文档仅有单一标题时显示目录
				 */
				desc: () => LocalizedString
			}
			hideHeadingNumberBlacklist: {
				/**
				 * 标题编号黑名单
				 */
				name: () => LocalizedString
				/**
				 * 指定需要隐藏标题编号的文件（每行一个路径）。支持通配符：* (任意字符)，? (单个字符)。仅在「使用标题编号」开启时生效。示例：folder/file.md 或 *.md
				 */
				desc: () => LocalizedString
			}
			enableDragSort: {
				/**
				 * 启用拖拽排序
				 */
				name: () => LocalizedString
				/**
				 * 允许在目录中拖拽标题来重新排序文档章节内容
				 */
				desc: () => LocalizedString
			}
		}
		tool: {
			/**
			 * 工具
			 */
			name: () => LocalizedString
			headings: {
				/**
				 * 文档导航按钮
				 */
				returnButtons: () => LocalizedString
				/**
				 * 目录工具栏按钮
				 */
				toolbarButtons: () => LocalizedString
			}
			useToolbar: {
				/**
				 * 使用工具栏
				 */
				name: () => LocalizedString
				/**
				 * 显示用于控制目录的工具栏（固定、位置、展开、偏移、复制）
				 */
				desc: () => LocalizedString
			}
			toolbarAlwaysShow: {
				/**
				 * 目录工具栏常驻显示
				 */
				name: () => LocalizedString
				/**
				 * 目录展开时，目录工具栏始终可见，无需悬停触发
				 */
				desc: () => LocalizedString
			}
			showProgressBar: {
				/**
				 * 显示进度条
				 */
				name: () => LocalizedString
				/**
				 * 在目录上方显示阅读进度
				 */
				desc: () => LocalizedString
			}
			showProgressCircle: {
				/**
				 * 显示进度圆环
				 */
				name: () => LocalizedString
				/**
				 * 在指示器上方显示阅读进度，即收缩目录后
				 */
				desc: () => LocalizedString
			}
			toolbarButtons: {
				pinTOC: {
					/**
					 * 固定/取消固定目录
					 */
					name: () => LocalizedString
					/**
					 * 切换目录是否常驻展开
					 */
					desc: () => LocalizedString
				}
				changePosition: {
					/**
					 * 更改位置
					 */
					name: () => LocalizedString
					/**
					 * 在左右两侧之间切换目录位置
					 */
					desc: () => LocalizedString
				}
				expandCollapse: {
					/**
					 * 展开/收起目录项
					 */
					name: () => LocalizedString
					/**
					 * 一键展开或收起所有目录项
					 */
					desc: () => LocalizedString
				}
				leftOffset: {
					/**
					 * 向左偏移
					 */
					name: () => LocalizedString
					/**
					 * 将目录向左移动一步
					 */
					desc: () => LocalizedString
				}
				rightOffset: {
					/**
					 * 向右偏移
					 */
					name: () => LocalizedString
					/**
					 * 将目录向右移动一步
					 */
					desc: () => LocalizedString
				}
				upOffset: {
					/**
					 * 向上移动
					 */
					name: () => LocalizedString
					/**
					 * 将目录向上移动一步
					 */
					desc: () => LocalizedString
				}
				downOffset: {
					/**
					 * 向下移动
					 */
					name: () => LocalizedString
					/**
					 * 将目录向下移动一步
					 */
					desc: () => LocalizedString
				}
				locateActiveHeading: {
					/**
					 * 定位到当前标题
					 */
					name: () => LocalizedString
					/**
					 * 滚动目录列表，使当前活动的标题进入可视范围
					 */
					desc: () => LocalizedString
				}
				copyTOC: {
					/**
					 * 复制目录
					 */
					name: () => LocalizedString
					/**
					 * 将目录复制到剪贴板
					 */
					desc: () => LocalizedString
				}
			}
			returnToCursor: {
				/**
				 * 返回光标
				 */
				name: () => LocalizedString
				/**
				 * 返回到上次光标位置的按钮（仅在编辑模式下可用）
				 */
				desc: () => LocalizedString
			}
			returnToTop: {
				/**
				 * 返回顶部
				 */
				name: () => LocalizedString
				/**
				 * 返回到文档顶部的按钮
				 */
				desc: () => LocalizedString
			}
			returnToBottom: {
				/**
				 * 返回底部
				 */
				name: () => LocalizedString
				/**
				 * 返回到文档底部的按钮
				 */
				desc: () => LocalizedString
			}
			jumpToNextHeading: {
				/**
				 * 跳转到下一个标题
				 */
				name: () => LocalizedString
				/**
				 * 跳转到下一个标题的按钮
				 */
				desc: () => LocalizedString
			}
			jumpToPrevHeading: {
				/**
				 * 跳转到上一个标题
				 */
				name: () => LocalizedString
				/**
				 * 跳转到上一个标题的按钮
				 */
				desc: () => LocalizedString
			}
		}
	}
	cards: {
		/**
		 * 预览
		 */
		preview: () => LocalizedString
		/**
		 * 属性
		 */
		property: () => LocalizedString
		/**
		 * 基本设置
		 */
		basicSetting: () => LocalizedString
		/**
		 * 样式设置
		 */
		styleSetting: () => LocalizedString
		readingTimeCard: {
			/**
			 * 阅读时间卡片设置
			 */
			heading: () => LocalizedString
			/**
			 * 标题
			 */
			title: () => LocalizedString
			/**
			 * 每分钟中文单词数
			 */
			chineseWordsPerMinute: () => LocalizedString
			/**
			 * 每分钟英文单词数
			 */
			englishWordsPerMinute: () => LocalizedString
			/**
			 * 阅读时间前的文本
			 */
			textBefore: () => LocalizedString
			/**
			 * 阅读时间后的文本
			 */
			textAfter: () => LocalizedString
			/**
			 * 图标名称（来自Obsidian图标集）
			 */
			iconName: () => LocalizedString
			/**
			 * 移除代码块
			 */
			removeCodeBlocks: () => LocalizedString
			/**
			 * 移除wiki链接
			 */
			removeWikiLinks: () => LocalizedString
			/**
			 * 移除图片链接
			 */
			removeImageLinks: () => LocalizedString
			/**
			 * 移除普通链接
			 */
			removeNormalLinks: () => LocalizedString
			/**
			 * 显示字数
			 */
			showWordCount: () => LocalizedString
		}
		tableOfContentsCard: {
			/**
			 * 目录卡片设置
			 */
			heading: () => LocalizedString
			/**
			 * 标题
			 */
			title: () => LocalizedString
			/**
			 * 最小标题深度
			 */
			minDepth: () => LocalizedString
			/**
			 * 最大标题深度
			 */
			maxDepth: () => LocalizedString
			/**
			 * 启用标题重定向
			 */
			redirect: () => LocalizedString
			/**
			 * 显示标题编号
			 */
			showNumbers: () => LocalizedString
			/**
			 * 使目录可折叠
			 */
			collapsible: () => LocalizedString
		}
		styles: {
			/**
			 * 当前属性
			 */
			currentProperties: () => LocalizedString
			/**
			 * 添加新属性
			 */
			addNewProperty: () => LocalizedString
			/**
			 * 未定义自定义属性
			 */
			noneCustomProperty: () => LocalizedString
		}
	}
	tools: {
		/**
		 * 固定/取消固定目录
		 */
		pinTOC: () => LocalizedString
		/**
		 * 更改目录位置
		 */
		changePosition: () => LocalizedString
		/**
		 * 展开/收起目录项
		 */
		expandCollapse: () => LocalizedString
		/**
		 * 向左偏移
		 */
		leftOffset: () => LocalizedString
		/**
		 * 向右偏移
		 */
		rightOffset: () => LocalizedString
		/**
		 * 向上移动
		 */
		upOffset: () => LocalizedString
		/**
		 * 向下移动
		 */
		downOffset: () => LocalizedString
		/**
		 * 定位到当前标题
		 */
		locateActiveHeading: () => LocalizedString
		/**
		 * 复制目录到剪贴板
		 */
		copyTOC: () => LocalizedString
		/**
		 * 返回导航
		 */
		returnNavigation: () => LocalizedString
		/**
		 * 返回光标位置
		 */
		returnToCursor: () => LocalizedString
		/**
		 * 返回顶部
		 */
		returnToTop: () => LocalizedString
		/**
		 * 返回底部
		 */
		returnToBottom: () => LocalizedString
		/**
		 * 下一个标题
		 */
		jumpToNextHeading: () => LocalizedString
		/**
		 * 上一个标题
		 */
		jumpToPrevHeading: () => LocalizedString
	}
}

export type Formatters = {}
