name: PR Close Debug

on:
    pull_request_target:
        types: [closed]
    pull_request:
        types: [closed]

jobs:
    debug-pr-close:
        runs-on: ubuntu-latest
        steps:
            - name: Debug PR close with pull_request_target
              if: github.event_name == 'pull_request_target'
              run: |
                  echo "=== pull_request_target Event ==="
                  echo "Event Name: ${{ github.event_name }}"
                  echo "Action: ${{ github.event.action }}"
                  echo "PR Number: ${{ github.event.number }}"
                  echo "Merged: ${{ github.event.pull_request.merged }}"
                  echo "State: ${{ github.event.pull_request.state }}"
                  echo "Head SHA: ${{ github.event.pull_request.head.sha }}"
                  echo "Base Branch: ${{ github.event.pull_request.base.ref }}"
                  echo "Repository: ${{ github.repository }}"
                  echo "Actor: ${{ github.actor }}"
                  echo "Workflow file path: ${{ github.workflow }}"

            - name: Debug PR close with pull_request
              if: github.event_name == 'pull_request'
              run: |
                  echo "=== pull_request Event ==="
                  echo "Event Name: ${{ github.event_name }}"
                  echo "Action: ${{ github.event.action }}"
                  echo "PR Number: ${{ github.event.number }}"
                  echo "Merged: ${{ github.event.pull_request.merged }}"
                  echo "State: ${{ github.event.pull_request.state }}"
                  echo "Head SHA: ${{ github.event.pull_request.head.sha }}"
                  echo "Base Branch: ${{ github.event.pull_request.base.ref }}"
                  echo "Repository: ${{ github.repository }}"
                  echo "Actor: ${{ github.actor }}"
                  echo "Workflow file path: ${{ github.workflow }}"

            - name: Check workflow file location
              run: |
                  echo "=== Workflow File Check ==="
                  echo "Current ref: ${{ github.ref }}"
                  echo "Default branch: ${{ github.event.repository.default_branch }}"
                  echo "Head ref: ${{ github.head_ref }}"
                  echo "Base ref: ${{ github.base_ref }}"

            - name: List recent workflow runs
              uses: actions/github-script@v7
              with:
                  script: |
                      try {
                          const runs = await github.rest.actions.listWorkflowRuns({
                              owner: context.repo.owner,
                              repo: context.repo.repo,
                              workflow_id: 'pr-build.yml',
                              per_page: 5
                          });
                          
                          console.log('Recent PR Build workflow runs:');
                          for (const run of runs.data.workflow_runs) {
                              console.log(`- Run ${run.id}: ${run.status} (${run.conclusion}) - ${run.event} - ${run.head_sha.substring(0,7)}`);
                          }
                      } catch (error) {
                          console.log('Error fetching workflow runs:', error.message);
                      }
